steps:  
- id: 'tf init'
  name: 'hashicorp/terraform:0.14.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ $_DEV_PLAN == $_PLAN_IN ]; then
        cd dev/terraform
        terraform init
      fi
      if [ $_PROD_PLAN == $_PLAN_IN ]; then
        cd prod/terraform
        terraform init
      fi

- id: 'tf plan'
  name: 'hashicorp/terraform:0.14.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ $_DEV_PLAN == $_PLAN_IN ]; then
        cd dev/terraform
        terraform plan
      fi
      if [ $_PROD_PLAN == $_PLAN_IN ]; then
        cd prod/terraform
        terraform plan
      fi

- id: 'tf apply'
  name: 'hashicorp/terraform:0.14.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ $_DEV_PLAN == $_PLAN_IN ] && [ $_DEV_APPLY == $_APPLY_IN ]; then
        cd dev/terraform
        terraform apply -auto-approve
      fi
      if [ $_PROD_PLAN == $_PLAN_IN ] && [ $_PROD_APPLY == $_APPLY_IN ]; then
        cd prod/terraform
        terraform apply -auto-approve
      fi

substitutions:
  _PLAN_IN: "DEV"
  _APPLY_IN: "DEV"
