steps:  
- id: 'tf init and tf plan'
  name: 'hashicorp/terraform:0.14.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo  "HEAD REPO URL::: $_HEAD_REPO_URL"
      echo  "REPO NAME::: $REPO_NAME"
      if [ $_ENV_TYPE != "PUSH" ]; then
        git clone $_GIT_REPO_URL
        cd $_REPO_DIR_PATH
        git checkout $_HEAD_BRANCH
        git diff --quiet $_HEAD_BRANCH remotes/origin/$_BASE_BRANCH -- dev/terraform || echo true > output.log
        if grep -q "true" output.log; then
          echo "inside loop"
          cd dev/terraform
          terraform init
          terraform plan
        fi
      fi

- id: 'tf init, tf plan and tf apply'
  name: 'hashicorp/terraform:0.14.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ $_ENV_TYPE == "PUSH" ]; then
        cd dev/terraform
        terraform init
        terraform plan
        terraform apply -auto-approve
      fi
