steps:  
- id: 'tf init'
  name: 'hashicorp/terraform:0.14.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo "Base $_BASE_BRANCH"
      echo "Head $_HEAD_BRANCH"
      echo "Branch $BRANCH_NAME"
      if [ $_CHECK_STATUS == "true" ]; then
        echo "inside init"
        cd dev/terraform
        terraform init
      fi

- id: 'tf plan'
  name: 'hashicorp/terraform:0.14.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ $_CHECK_STATUS == "true" ]; then
        echo "inside plan"
        cd dev/terraform
        terraform plan
      fi
      echo "Base $_BASE_BRANCH"
      echo "Head $_HEAD_BRANCH"
      echo "Branch $BRANCH_NAME"

- id: 'tf apply'
  name: 'hashicorp/terraform:0.14.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ $_ENV_TYPE == "PUSH" ]; then
        cd dev/terraform
        terraform apply -auto-approve
      fi

substitutions:
  _CHECK_STATUS: "true"
