steps:  
- id: 'tf init'
  name: 'hashicorp/terraform:0.14.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd dev/terraform
      terraform init

# Comments

- id: 'tf plan'
  name: 'hashicorp/terraform:0.14.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd dev/terraform
      terraform plan

- id: 'tf apply'
  name: 'hashicorp/terraform:0.14.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ $_ENV_TYPE == "PUSH" ]; then
        cd dev/terraform
        terraform apply -auto-approve
      fi
