steps:  
- id: 'tf init'
  name: 'hashicorp/terraform:0.14.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd prod
      check_status=$(git diff --quiet $_HEAD_BRANCH $_BASE_BRANCH -- terraform || echo true)
      echo "Base $_BASE_BRANCH"
      echo "Head $_HEAD_BRANCH"
      echo "Branch $BRANCH_NAME"
      if [[ $check_status ]]
      then
        echo "inside init"
        cd terraform
        terraform init
      fi

- id: 'tf plan'
  name: 'hashicorp/terraform:0.14.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd prod
      check_status=$(git diff --quiet $_HEAD_BRANCH $_BASE_BRANCH -- terraform || echo true)
      echo "Base $_BASE_BRANCH"
      echo "Head $_HEAD_BRANCH"
      echo "Branch $BRANCH_NAME"
      if [[ $check_status ]]
      then
        echo "inside plan"
        terraform plan
      fi

- id: 'tf apply'
  name: 'hashicorp/terraform:0.14.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ $_ENV_TYPE == "PUSH" ]; then
        cd prod/terraform
        terraform apply -auto-approve
      fi
