steps:  
- id: 'tf init'
  name: 'hashicorp/terraform:0.14.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ $_CHECK_STATUS == "true" ]; then
        echo "inside init"
        cd prod/terraform
        terraform init
      fi
      echo "Base $_BASE_BRANCH"
      echo "Head $_HEAD_BRANCH"
      echo "Branch $BRANCH_NAME"

- id: 'tf plan'
  name: 'hashicorp/terraform:0.14.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo "*********"
      git diff $_HEAD_BRANCH remotes/origin/$_BASE_BRANCH -- prod/terraform
      echo "*********"
      echo "#########"
      git diff --quiet $_HEAD_BRANCH remotes/origin/$_BASE_BRANCH -- prod/terraform || echo true
      echo "#########"
      if [ $_CHECK_STATUS == "true" ]; then
        echo "inside plan"
        cd prod/terraform
        terraform plan
      fi

- id: 'tf apply'
  name: 'hashicorp/terraform:0.14.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ $_ENV_TYPE == "PUSH" ]; then
        cd prod/terraform
        terraform apply -auto-approve
      fi

substitutions:
  _CHECK_STATUS: "true"

options:
    substitution_option: 'ALLOW_LOOSE'
