steps:  
- id: 'tf init'
  name: 'hashicorp/terraform:0.14.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo ""

- id: 'tf plan'
  name: 'hashicorp/terraform:0.14.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      git clone https://github.com/kyeswanth/solutions-terraform-cloudbuild-gitops.git
      cd solutions-terraform-cloudbuild-gitops
      git checkout $_HEAD_BRANCH
      rm prod/terraform/variables.tf
            git diff --quiet $_HEAD_BRANCH remotes/origin/$_BASE_BRANCH -- prod/terraform
      git status

- id: 'tf apply'
  name: 'hashicorp/terraform:0.14.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ $_ENV_TYPE == "PUSH" ]; then
        cd prod/terraform
        terraform apply -auto-approve
      fi

substitutions:
  _CHECK_STATUS: "true"

options:
    substitution_option: 'ALLOW_LOOSE'
