steps:  
- id: 'tf init'
  name: 'hashicorp/terraform:0.14.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo "Base $_BASE_BRANCH"
      echo "Head $_HEAD_BRANCH"
      echo "Branch $BRANCH_NAME"
      check_status=$(git diff --quiet $_HEAD_BRANCH $_BASE_BRANCH -- prod/terraform || echo true);
      echo "Status $check_status"
      if [[ false ]]
      then
        echo "inside init"
        cd prod/terraform
        terraform init
      fi

- id: 'tf plan'
  name: 'hashicorp/terraform:0.14.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      echo "Base $_BASE_BRANCH"
      echo "Head $_HEAD_BRANCH"
      echo "Branch $BRANCH_NAME"
      check_status=$(git diff --quiet $_HEAD_BRANCH $_BASE_BRANCH -- prod/terraform || echo true);
      echo "Status $check_status"
      if [[ false ]]
      then
        echo "inside plan"
        cd prod/terraform
        terraform plan
      fi

- id: 'tf apply'
  name: 'hashicorp/terraform:0.14.6'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ $_ENV_TYPE == "PUSH" ]; then
        cd prod/terraform
        terraform apply -auto-approve
      fi
